### ISSUE TITLE
object HockeyAppUnityIOS not found

### ISSUE THREAD

**Issue by antifuzz** [bitstadium/HockeySDK-Unity-iOS#13]
I've followed the implementation guide, and checked and re-checked everything, but when I run my app, I'm getting the following message in XCode's debugger:

SendMessage: object HockeyAppUnityIOS not found!

The app doesn't crash, and appears to run fine, but I get no reports in Hockey. 

I'm using Version 1.0.4 and have tried it in Unity 4.6.2p1 and 4.6.5.
Any ideas?
Thanks!

**Comment by chrs1885** [comment]
What's the name of your Unity Game object, which holds the hockey script as one of it's components?

**Comment by antifuzz** [comment]
Thanks for the fast response Chris, yes my game object was named wrong. Renamed it to HockeyAppUnityIOS and now it's working.
:)
