### ISSUE TITLE
iOS Runtime issue in HockeyApp_StartHockeyManager: unrecognized selector

### ISSUE THREAD

**Issue by jefferychow** [bitstadium/HockeySDK-Unity-iOS#15]
I got my iOS project compiling and linking but at runtime xcode crashes with the following:

2015-06-01 17:10:40.258 crossfire[9856:876924] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[HockeyAppUnity startManagerWithIdentifier:serverUrl:authType:secret:updateManagerEnabled:autoSendEnabled:]: unrecognized selector sent to class 0x1d9654c'

Inside the call HockeyApp_StartHockeyManager in HockeyAppUnityWrapper.m.

**Comment by jefferychow** [comment]
1.0.6 btw.

**Comment by chrs1885** [comment]
Which version of Unity are you using?

**Comment by jefferychow** [comment]
5.0.2p3, sorry.

**Comment by jefferychow** [comment]
Let me compile my own .a file real quick (https://github.com/bitstadium/HockeySDK-Unity-iOS/tree/master/UnityPluginSources) and see if that makes a difference

**Comment by jefferychow** [comment]
So I noticed that the two versions of the file HockeyAppUnity.h (the one used by xcode to generate iOS app and the one used to create the .a file) has a discrepancy in the capitalization of the 'serverURL' parameter: http://www.screencast.com/t/C6l0XUi4SO.

The .m file uses serverURL but the former .h file uses 'serverUrl'. I changed it to 'serverURL' and it seemed to fix it.
