### ISSUE TITLE
The post build script PostBuildTrigger.cs removes too many lines before appending to the end of the method when using Position.End 

### ISSUE THREAD

**Issue by craigrushforth** [bitstadium/HockeySDK-Unity-iOS#19]
It removes necessary lines from the original source code E.g.
	
[UIView setAnimationsEnabled:YES];

at the end of method 
- (void)showGameUI

Which stops keyboard open/close animations from happening.

Should change the -3 to -1 (to only remove a single line) in the method 'InsertCodeIntoClass'
newContents = newContents.GetRange(0, newContents.Count - 3);

Anyway thanks fore the plugin.  Much appreciated.

**Comment by lumaxis** [comment]
Thanks @craigrushforth for reporting this! We'll look into this and come up with a fix as soon as we can. Just in case you already know the necessary steps and maybe even have a working fix, we are happy to accept Pull Requests! :)

**Comment by chrwend** [comment]
Fixed in 65e035cdaa399cb3478ee3e88fc439c29cd43e36
