### ISSUE TITLE
Crash when first launching game without internet

### ISSUE THREAD

**Issue by ShaneLillieGlu** [bitstadium/HockeySDK-Unity-iOS#22]
There's an issue with both HockeySDK-Unity-IOS and HockeySDK-Unity-Android where if the game is installed and launched, the first time, without any internet connection (ie, IsConnected() returns false), the log directory is never created and an exception will occur on the first Debug.LogError() call, which the SDK attempts to write to a file that cannot be created, because the directory does not exist.

I've fixed this in my game's code by creating the directory explicitly in Awake() in both of the HockeyApp behaviors - rather than relying on SendLogs() to do it since that is dependent on IsConnected() returning true - and by wrapping the WriteLogToDisk() contents in a try/catch block, just to be safe. I can create a pull request with those changes if desired, but I reckon its simple enough that it probably isn't worth the effort on either end to deal with that.

**Comment by chrwend** [comment]
Good catch, this fix will be part of the next release! Thank you

**Comment by chrwend** [comment]
@ShaneLillieGlu: I've created a [feature-branch per platform](https://github.com/bitstadium/HockeySDK-Unity-iOS/tree/feature/fix-log-directory-creation). Thank you.
