### ISSUE TITLE
PostBuildTrigger removes too many lines during replace operation.

### ISSUE THREAD

**Issue by doggan** [bitstadium/HockeySDK-Unity-iOS#28]
This fix https://github.com/bitstadium/HockeySDK-Unity-iOS/commit/65e035cdaa399cb3478ee3e88fc439c29cd43e36 seems to have been inadvertently reverted by this commit https://github.com/bitstadium/HockeySDK-Unity-iOS/commit/29afe1dff964eb3d898c8a1b0308074d5a15e7e2.

This causes the HockeyApp post-processor to clobber existing code while appending at the end.

Depending on the version of Unity being used and/or other included plugins, this results in a wide range of issues. On Unity 5.4.4 for example, native UI will no longer animated due to `[UIView setAnimationsEnabled:YES];` being clobbered.

**Comment by lumaxis** [comment]
@doggan Thanks for reporting this! Do you think you would be able to put together a quick Pull Request to fix this again? Otherwise it might take us a few days until we get to this ourselves. Any help would be highly appreciated 😊

**Comment by doggan** [comment]
@lumaxis done!~
