### ISSUE TITLE
Custom events 

### ISSUE THREAD

**Issue by deadlyfingers** [bitstadium/HockeySDK-Unity-iOS#30]
Are custom events supported in Unity plugin for iOS? 
https://support.hockeyapp.net/kb/general-account-management-2/getting-started-with-custom-events-public-preview

If so, be good to add it to the Unity example script:
https://github.com/bitstadium/HockeySDK-Unity-iOS/blob/master/ExampleGame/Assets/TestUI/TestUI.cs

**Comment by chrwend** [comment]
@deadlyfingers: Unfortunately, custom events are not yet supported by the Unity plugin and there is no plan to support it in the near future.
