### ISSUE TITLE
Plugin resides in the wrong folder

### ISSUE THREAD

**Issue by Skjalgsm** [bitstadium/HockeySDK-Unity-iOS#31]
Hi

This is something that has been bothering me for a very long time with this asset. It resides in Plugin/HockeyAppUnityIOS when it should reside in Plugin**s**/HockeyAppUnityIOS (plural s) 
![image](https://user-images.githubusercontent.com/568589/28874379-e6e37aa0-7791-11e7-9329-cc6fcd84e102.png)

**Comment by Skjalgsm** [comment]
Just moving the folder does not work, because then the xcode project does not compile.

[33m▸[0m [39;1mCompiling[0m UnityAppController.mm

[31m❌  [0m/Users/../../../jobs/iOS Beta/workspace/Build/Classes/UnityAppController.mm:1:9: [31m'HockeyAppUnity.h' file not found[0m

#import "HockeyAppUnity.h"

**Comment by Skjalgsm** [comment]
Seems like moving the folder worked after all.

**Comment by TroubleMakerBen** [comment]
Hi @Skjalgsm,
Thx for bringing this up. We'll see what we can do for the next release. 
Benny

**Comment by TroubleMakerBen** [comment]
We've renamed the folder. Sorry it took us so long to fix this.

Cheers!
Benny
