### ISSUE TITLE
Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by Skjalgsm** [bitstadium/HockeySDK-Unity-iOS#32]
I get these errors when I install this plugin into my project

15:30:48 [31m❌  Undefined symbols for architecture arm64[0m
15:30:48 > Symbol: _HockeyApp_CheckForUpdate
15:30:48 > Referenced from: _HockeyAppIOS_HockeyApp_CheckForUpdate_m2036374157 in Bulk_Assembly-CSharp_3.o
15:30:48 
15:30:48 
15:30:48 
15:30:48 [31m❌  ld: symbol(s) not found for architecture arm64[0m
15:30:48 
15:30:48 
15:30:48 
15:30:48 [31m❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)[0m
15:30:48 
15:30:48 
15:30:48 [33m▸[0m [39;1mLinking[0m grisene
15:30:48 
15:30:48 [31m❌  Undefined symbols for architecture armv7[0m
15:30:48 > Symbol: _HockeyApp_CheckForUpdate
15:30:48 > Referenced from: _HockeyAppIOS_HockeyApp_CheckForUpdate_m2036374157 in Bulk_Assembly-CSharp_3.o

**Comment by Skjalgsm** [comment]
Ah, the meta files for some of the files did not specifically tell unity that they were needed on the ios platform.

You need to change the settings for some of the files to look like this and this should be fixed

![image](https://user-images.githubusercontent.com/568589/28877005-5b7d3136-779b-11e7-85a3-eefa444ffbe3.png)

**Comment by TroubleMakerBen** [comment]
Hey!
I tried to get this reproduced and couldn't.
Can you try with today's release, please?

Best,
Benny

**Comment by TroubleMakerBen** [comment]
I'm not able to reproduce the issue and haven't heard from you. I'm closing this but feel free to open it again, in case you see this happen to you again.
