### ISSUE TITLE
Localized strings not working in v5.0.0

### ISSUE THREAD

**Issue by atraver** [bitstadium/HockeySDK-Unity-iOS#36]
After upgrading from v1.1.8 to v5.0.0, we noticed that string localization has stopped working. Everywhere a localized string should be shown, its key is shown instead. For example:

![image](https://user-images.githubusercontent.com/6304/33844693-e9e81ec4-de55-11e7-8de0-cd364e515d7a.png)

![image](https://user-images.githubusercontent.com/6304/33844711-f4b39612-de55-11e7-8285-1c6349ea7656.png)

Everything works fine when doing the update workflow, we just have these ugly strings. The `HockeySDK.strings` file is present under `Plugins/HockeyAppUnityIOS/HockeySDKResources.bundle/en.lproj` (we copied the entire plugin for the release and removed the old plugin at the `Assets` level).

Any ideas?

**Comment by MatkovIvan** [comment]
Hi Adam,

Thank you for getting in touch.
To resolve this issue select `HockeySDKResources.bundle` in the **Project** view and make sure that **iOS** is selected in **Select platforms for plugin** section in the **Inspector** view.

Best,
Ivan

**Comment by atraver** [comment]
Looks like that did the trick. Thanks, Ivan!
