### ISSUE TITLE
PNG files could not be read

### ISSUE THREAD

**Issue by kefniark** [bitstadium/HockeySDK-Unity-iOS#48]
## Description
We use both android and ios hockey app plugin on a unity project, but the IOS plugin create a certain amount of warning:
![image](https://user-images.githubusercontent.com/4903529/35372759-eed4a54a-01de-11e8-94bf-3dc857c92cba.png)
We can still start the project and use those plugins, but we have these errors every time we reimport or switch platform.

It seems related to https://answers.unity.com/questions/697438/why-am-i-getting-an-error-for-png-files-in-an-ios.html

## Spec:
* Unity 2017.x
* Windows 10
* Hockey app Plugin:
   * Installed from the store https://assetstore.unity.com/packages/tools/integration/hockeysdk-for-unity-ios-17757
   * Version 5.1.0 (but it was already happening before)

**Comment by TroubleMakerBen** [comment]
Hi @kefniark,

thx for getting in touch. We have been trying to resolve this in the past but with no luck =(
That said, you should be able to use the HockeyApp plugins just fine and be able to ignore the warning.

I'll create another task for it and update this issue accordingly.

Best,
Benjamin
